/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { QuizPackagesWhereUniqueInput } from "../../quizPackages/base/QuizPackagesWhereUniqueInput";
import { UserLobbiesListRelationFilter } from "../../userLobbies/base/UserLobbiesListRelationFilter";

@InputType()
class LobbiesWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  code?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  host?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  hostId?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  hostUser?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lobbiesQuizPackage?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => QuizPackagesWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => QuizPackagesWhereUniqueInput)
  @IsOptional()
  @Field(() => QuizPackagesWhereUniqueInput, {
    nullable: true,
  })
  quizPackage?: QuizPackagesWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => UserLobbiesListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserLobbiesListRelationFilter)
  @IsOptional()
  @Field(() => UserLobbiesListRelationFilter, {
    nullable: true,
  })
  userLobbiesItems?: UserLobbiesListRelationFilter;
}

export { LobbiesWhereInput as LobbiesWhereInput };
